version: 2
updates:
- package-ecosystem: nuget
  directory: "/backend"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Swashbuckle.AspNetCore
    versions:
    - 5.6.3
    - 6.0.2
    - 6.0.4
    - 6.0.5
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: Microsoft.AspNetCore.Mvc.Testing
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.TestHost
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
  - dependency-name: Moq
    versions:
    - 4.16.0
